In [30]:
# Name: Chhayank Sharma
# Registration no.: 60
# For the CEREALS dataset, perform data preprocessing and answer the following questions.
# a. Create a table with the 5 number summary of all the numeric attributes.
# b. For each of the numeric attributes(proteins upto vitamins),
#    identify and replace all missing data(indicated with -1) with the arithmetic mean of the attribute.
# c. Create a table with the 5 number summary of all the numeric attributes after treating missing values.
#    Do you think the strategy used in dealing with missing values was effective?
# d. For each numeric attribute (proteins upto vitamins), identify and replace all noisy data with the median of attribute.
# e. Create a table with the 5 number summary of all the numeric attributes after treating noisy values.
#    Do you think the strategy used in dealing with noisy values was effective?

In [31]:
import numpy as np
import pandas as pd

In [32]:
cerealdata = pd.DataFrame(pd.read_csv('cereal.csv'))
cerealdata

,Cereal Name,Manufacturer,Type,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
0,100%_Bran,Nabisco,C,70,4,1,130,10.0,5.0,6,3,280,25,1.0,0.33
1,100%_Natural_Bran,Quaker Oats,C,120,3,5,15,2.0,8.0,8,3,135,0,1.0,-1.00
2,All-Bran,Kelloggs,C,70,4,1,260,9.0,7.0,5,3,320,25,1.0,0.33
3,All-Bran_with_Extra_Fiber,Kelloggs,C,50,4,0,140,14.0,8.0,0,3,330,25,1.0,0.50
4,Almond_Delight,Ralston Purina,C,110,2,2,200,1.0,14.0,8,3,-1,25,1.0,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Triples,General Mills,C,110,2,1,250,0.0,21.0,3,3,60,25,1.0,0.75
70,Trix,General Mills,C,110,1,1,140,0.0,13.0,12,2,25,25,1.0,1.00
71,Wheat_Chex,Ralston Purina,C,100,3,1,230,3.0,17.0,3,1,115,25,1.0,0.67
72,Wheaties,General Mills,C,100,3,1,200,3.0,17.0,3,1,110,25,1.0,1.00
73,Wheaties_Honey_Gold,General Mills,C,110,2,1,200,1.0,16.0,8,1,60,25,1.0,0.75

In [33]:
cerealdata.describe()[3:]

,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
min,50.0,1.0,0.0,0.00,0.00,-1.0,-1.00,1.0,-1.00,0.0,0.5,-1.00
25%,100.0,2.0,0.0,131.25,0.25,12.0,3.00,1.0,40.00,25.0,1.0,0.67
50%,110.0,2.0,1.0,180.00,1.50,14.0,6.00,2.0,90.00,25.0,1.0,0.75
75%,110.0,3.0,1.0,217.50,3.00,17.0,10.75,3.0,113.75,25.0,1.0,1.00
max,160.0,6.0,5.0,320.00,14.00,23.0,15.00,3.0,330.00,100.0,1.5,1.50

In [36]:
cerealdata.loc[:,"Protein (g)":"Vitamins and Minerals"]=cerealdata.loc[:,"Protein (g)":"Vitamins and Minerals"].replace(-1, cerealdata.mean(numeric_only=True))

In [37]:
cerealdata.describe()[3:]

,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
min,50.0,1.0,0.0,0.00,0.00,5.000000,0.000000,1.0,15.00,0.0,0.5,-1.00
25%,100.0,2.0,0.0,131.25,0.25,12.000000,3.000000,1.0,41.25,25.0,1.0,0.67
50%,110.0,2.0,1.0,180.00,1.50,14.297297,6.385135,2.0,90.00,25.0,1.0,0.75
75%,110.0,3.0,1.0,217.50,3.00,17.000000,10.750000,3.0,113.75,25.0,1.0,1.00
max,160.0,6.0,5.0,320.00,14.00,23.000000,15.000000,3.0,330.00,100.0,1.5,1.50

In [38]:
cerealdata.loc[:,"Protein (g)":"Vitamins and Minerals"].fillna(cerealdata.median(numeric_only=True))

,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals
0,4,1,130,10.0,5.0,6.0,3,280.000000,25
1,3,5,15,2.0,8.0,8.0,3,135.000000,0
2,4,1,260,9.0,7.0,5.0,3,320.000000,25
3,4,0,140,14.0,8.0,0.0,3,330.000000,25
4,2,2,200,1.0,14.0,8.0,3,92.675676,25
...,...,...,...,...,...,...,...,...,...
69,2,1,250,0.0,21.0,3.0,3,60.000000,25
70,1,1,140,0.0,13.0,12.0,2,25.000000,25
71,3,1,230,3.0,17.0,3.0,1,115.000000,25
72,3,1,200,3.0,17.0,3.0,1,110.000000,25
73,2,1,200,1.0,16.0,8.0,1,60.000000,25

In [39]:
cerealdata.describe()[3:]

,Calories,Protein (g),Fat,Sodium,Dietary Fiber,Carbs,Sugars,Display Shelf,Potassium,Vitamins and Minerals,Serving Size Weight,Cups per Serving
min,50.0,1.0,0.0,0.00,0.00,5.000000,0.000000,1.0,15.00,0.0,0.5,-1.00
25%,100.0,2.0,0.0,131.25,0.25,12.000000,3.000000,1.0,41.25,25.0,1.0,0.67
50%,110.0,2.0,1.0,180.00,1.50,14.297297,6.385135,2.0,90.00,25.0,1.0,0.75
75%,110.0,3.0,1.0,217.50,3.00,17.000000,10.750000,3.0,113.75,25.0,1.0,1.00
max,160.0,6.0,5.0,320.00,14.00,23.000000,15.000000,3.0,330.00,100.0,1.5,1.50